### ISSUE TITLE
improve gap rendering

### ISSUE THREAD

**Issue by holfordm** [msDesc/consolidated-tei-schema#40]
currently all gaps are rendered as ... since all `gap` elements are matched by the template at msdesc2html line 859. It would be better (1) to distinguish between editorial gaps (where text has been deliberately omitted) and gaps due to damage or illegibility and (2) in the case to damage or illegibility to indicate by dots the quantity of missing text, if this is specified in the TEI.

**Comment by andrew-morrison** [comment]
Regarding (2), there already are templates in the XSLT for displaying as many dots as specified in either `@quantity` or `@extent`, but not only if `@unit` is "chars" (not if it is "char" which is one of the suggested values in the TEI P5 schema, or "character" which has also been used in some of the St. John's College records).

[In the documentation](https://msdesc.github.io/consolidated-tei-schema/msdesc.html#transcription), there are examples using `@atLeast` and `@atMost` which won't work either.

There are also some instances in the Medieval catalogue when it looks like `@n` has been used instead of  `@quantity` or `@extent`, which is incorrect.
